### ISSUE TITLE
launch.json python attach not working in latest vscode (1.29.1)

### ISSUE THREAD

**Issue by kcoley** [AlansCodeLog/blender-debugger-for-vscode#10]
OS: Windows 10

Add-on Version: 0.2.0

Blender Version: 2.79

VS Code Version: 1.29.1

VS Code Python Extension Version: 2018.10.1

PTVSD Version: 3.0.0

Paths listed by `where python` or the corresponding command:

Does VS Code / Visual Studio connect to the troubleshooting script? yes

## Notes:
Great tool!  Though to get it to work with my build of VSCode, I had to change the `launch.json` syntax to this: 

```json
{
            "name": "Python: Attach",
            "type": "python",
            "request": "attach",
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "${workspaceFolder}"
                }
            ],
            "port": 3000,
            "host": "localhost"
        }
```
Afterwards, everything seems to work as expected.  I would make a PR, though I am not sure if any other users have hit this issue.

**Comment by alanscodelog** [comment]
You should actually just be able to do this, without the remote root mappings.

```json
   {
      "name": "Python: Attach",
      "type": "python",
      "request": "attach",
      "port": 3000,
      "host": "localhost"
   },
```

I will update the documentation soon on this since the port number will also be changing from 3000 to 5678.

**Comment by kcoley** [comment]
@AlansCodeLog thanks for the follow up!  Yes, it works without the root mappings.
