### ISSUE TITLE
Transition to debugpy ?

### ISSUE THREAD

**Issue by CyrilWaechter** [AlansCodeLog/blender-debugger-for-vscode#19]
OS: Any

Add-on Version: Future

Blender Version: 2.90.1

VS Code Version: 1.49.1

VS Code Python Extension Version: v2020.9.112786

PTVSD Version: 4.3.2

Paths listed by `where python` or the corresponding command:

Does VS Code / Visual Studio connect to the troubleshooting script? No

Python path/interpreter detected/selected by VS Code/Visual Studio: Yes

## Notes:
[debugpy](https://github.com/microsoft/debugpy) apparently replace ptvsd as standard [debugging tool](https://github.com/microsoft/debugpy). I was using ptvsd before but now fail to attach anything (not related to this addon or Blender. As fallback I currently embed ipython as explained in [Tips and Tricks](https://docs.blender.org/api/current/info_tips_and_tricks.html) which is not as handy as ptvsd/debugpy). Have you tried to use debugpy instead ? Have you already plan to transition to debugpy ?

(I would happy to help transition with a pull request but I currently fail to attach at all even manually)

**Comment by alanscodelog** [comment]
Didn't know about this (haven't used Blender for addon development in a while), thanks! 

Have you tried changing this [test script](https://gist.github.com/AlansCodeLog/ff1b246a8e31938e1c3dbfdcbb90522f) to use debugpy? Close blender just in case and run it with python and try to attach to it with vs code. If you can get it to work, it's fairly easy to transfer the changes needed to the add on.

**Comment by CyrilWaechter** [comment]
Hi,
Sorry for late answer. I have yet not been able to make it work. I’ll try again later.

**Comment by tettoffensive** [comment]
Was wondering why I couldn't get this setup to work. I'm thinking it's because of this.

**Comment by tettoffensive** [comment]
I opened a pull request #24 I tested this out and it worked for me
