### ISSUE TITLE
No field "Location of PTVSD"

### ISSUE THREAD

**Issue by Ericetto** [AlansCodeLog/blender-debugger-for-vscode#21]
OS: Windows 10
Add-on Version: 1.0.0
Blender Version: 2.79.6
VS Code Version: 1.50.1
VS Code Python Extension Version:  v2020.10.332292344
PTVSD Version: 3.0.0
Paths listed by `where python` command:
 ```
C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\python\bin\python.exe
C:\Users\e.imashev\AppData\Local\Microsoft\WindowsApps\python.exe
```
Python path/interpreter selected by VS Code:
`C:\Program Files\Chaos Group\Blender 2.79 (With V-Ray Additions)\2.79\python\bin\python.exe`

Hello, Allan!

I have no field "Location of PTVSD", so I can't set path to it. 
![image](https://user-images.githubusercontent.com/28396245/97572410-3ca61300-19f9-11eb-9bd3-19279ebf9dbf.png)

And when I try make "Debug: Start Debug Server for VS Code" command, I get this error:

```
 Traceback (most recent call last):
  File "C:\Users\e.imashev\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\blender-debugger-for-vscode-master\__init__.py", line 169, in execute
    prefs = bpy.context.preferences.addons[__name__].preferences
AttributeError: 'Context' object has no attribute 'preferences'
location: <unknown location>:-1
```

**Comment by alanscodelog** [comment]
For Blender 2.79 you should be using version [0.3.0](https://github.com/AlansCodeLog/blender-debugger-for-vscode/releases/tag/0.3.0). 1.0.0 is for Blender 2.8+

I'm pretty sure this is the problem so I will close the issue, but feel free to re-open it if you're still having problems.

**Comment by Ericetto** [comment]
I apologize for my inattention, you are right, thank you!
