### ISSUE TITLE
debuger can not detect file changes in other directory

### ISSUE THREAD

**Issue by derrick-xwp** [AlansCodeLog/blender-debugger-for-vscode#25]
debuger can not detect file changes in other directory

**Comment by alanscodelog** [comment]
Please provide more info, what steps did you take, what went wrong? I do not understand the problem. 

And please fill out at least the versions on the issue template: https://github.com/AlansCodeLog/blender-debugger-for-vscode/blob/master/ISSUE_TEMPLATE.md

And did you figure out your problem in #23 ?
