### ISSUE TITLE
Does the addon work in other modes?

### ISSUE THREAD

**Issue by Amir-Arsalan** [AlansCodeLog/blender-debugger-for-vscode#7]
Hi. In your video you say that your addon only works in Sculpt Mode. I wonder, have you made any changes to it since then so that it works in other modes as well?

**Comment by alanscodelog** [comment]
Hi, I think you misunderstood. It works anywhere in Blender, I was just using an addon I'm developing (it's over [here](https://github.com/AlansCodeLog/blender-useful-menus-addon) if you're curious) as an example to show how to set everything up, and that addon happens to be for sculpt mode so I had to go to sculpt mode to trigger the breakpoint I'd set in vs code.

**Comment by Amir-Arsalan** [comment]
@AlansCodeLog Sorry my bad. I totally mixed things up.
